#!/usr/bin/python

import sched, time, datetime
from subprocess import call

def scrape():
  print('Launching scraper - ' + str(datetime.datetime.now().time()))
  call(['./scraper', '--workers=2'])
  s.enter(7, 1, scrape, ())

s = sched.scheduler(time.time, time.sleep)
s.enter(7, 1, scrape, ())
s.run()
